services:
  # ----- NGINX -----
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: requirements/nginx
    ports:
      - 443:443
    networks:
      - inception_network
    volumes:
      - wordpress:/var/www/html/wordpress
    restart: on-failure
    env_file:
      - ./.env
  
  # ----- WORDPRESS -----
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    build: requirements/wordpress
    networks:
      - inception_network
    restart: on-failure
    volumes:
      - wordpress:/var/www/html/wordpress
    env_file:
      - ./.env

  # ----- MARIADB -----
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    networks:
      - inception_network
    ports:
      - 3306
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - ./.env
    restart: on-failure
  # ----- REDIS -----
  redis:
    container_name: redis
    build: requirements/bonus/redis
    networks:
      - inception_network
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    restart: on-failure
    env_file:
      - ./.env

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: $HOME/$LOGIN/data/wordpress
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: $HOME/$LOGIN/data/mariadb
      o: bind
  redis:
    driver: local
    driver_opts:
      type: none
      device: $HOME/$LOGIN/data/redis
      o: bind

networks:
  inception_network:
    driver: bridge
