services:
  # ----- NGINX -----
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: requirements/nginx
    ports:
      - 443:443
    networks:
      - inception_network
    volumes:
      - wordpress:/var/www/html/wordpress
    restart: on-failure
    env_file:
      - ./.env
  
  # ----- WORDPRESS -----
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    build: requirements/wordpress
    networks:
      - inception_network
    restart: on-failure
    volumes:
      - wordpress:/var/www/html/wordpress
    env_file:
      - ./.env

  # ----- MARIADB -----
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    networks:
      - inception_network
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - ./.env
    restart: on-failure

  # ----- REDIS -----
  redis:
    container_name: redis
    build: requirements/bonus/redis
    networks:
      - inception_network
    restart: on-failure
    env_file:
      - ./.env

  # ----- FTP -----
  ftp:
    depends_on:
      - wordpress
    container_name: ftp
    build: requirements/bonus/ftp
    networks:
      - inception_network
    ports:
      - "21:21"
      - "20:20"
      - "21100-21110:21100-21110"
    volumes:
      - wordpress:/home/vsftpd
    restart: on-failure
    env_file:
      - ./.env

  # ----- STATIC_WEBSITE -----
  static_website:
    container_name: static_website
    build: requirements/bonus/static_website
    networks:
      - inception_network
    ports:
      - "8000:8000"
    restart: on-failure
    env_file:
      - ./.env

  # ----- ADMINER -----
  adminer:
    container_name: adminer
    depends_on:
      - wordpress
    build: requirements/bonus/adminer
    networks:
      - inception_network
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html/wordpress
    restart: on-failure
    env_file:
      - ./.env

  # ----- PORTAINER -----
  portainer:
    container_name: portainer
    build: requirements/bonus/portainer
    networks:
      - inception_network
    ports:
      - "9001:9000"
    restart: on-failure
    env_file:
      - ./.env

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: $HOME/$LOGIN/data/wordpress
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: $HOME/$LOGIN/data/mariadb
      o: bind

networks:
  inception_network:
    driver: bridge
